#!/bin/csh -f

##setenv LD_LIBRARY_PATH /usr/local/cuda/nvvm/lib:/usr/local/cuda/lib64:/usr/local/opencv3/lib
g++ -I/usr/local/opencv3/include capture.cpp -L/usr/local/opencv3/lib -lopencv_core -lopencv_videoio -lopencv_highgui -lopencv_imgproc -o cap
